
!ifdef SHOW_SP2
	box "Service Provider 2"
		participant "Msg Server" as SP2
		!ifdef SHOW_Msg2
			participant "Msg Service" as Msg2
		!endif
	end box

!endif

!ifdef SHOW_RuntimeB

	!ifdef SHOW_AppAtRuntimeB
		participant "App" as App@B
	!endif

	!ifdef SHOW_NativeAtRuntimeB
		box "Bob Native Runtime"
			!ifdef SHOW_WebRTCAtRuntimeB
				participant "WebRTC" as WRTC
			!endif

			!ifdef SHOW_JavascriptEngineAtRuntimeB
				participant "JavaScript Runtime" as JS
			!endif
		end box
	!endif

	!ifdef SHOW_CoreRuntimeB
		box "Bob Core Runtime"

			!ifdef SHOW_RegistryAtRuntimeB
				participant "Registry" as RunReg@B
			!endif

			!ifdef SHOW_IdentitiesAtRuntimeB
				participant "Identities" as RunID@B
			!endif

			!ifdef SHOW_AuthAtRuntimeB
				participant "Authorisation" as RunAuth@B
			!endif
			!ifdef SHOW_MsgBUSAtRuntimeB
				participant "Msg BUS" as BUS@B
			!endif
		end box
	!endif

	!ifdef SHOW_SP1SandboxAtRuntimeB
		box "Service Provider 1 Sandbox at Bob Device"

			!ifdef SHOW_ServiceProvider1HypertyAtRuntimeB
			participant "Service Provider1\nHyperty" as SP1H@B
			!endif

			!ifdef SHOW_ServiceProvider1RouterAtRuntimeB
			participant "Service Provider1\nRouter" as Router1@B
			!endif

			!ifdef SHOW_IdentityObjectAtRuntimeB
			participant "Identity\nData Object" as IDObj@B
			!endif

			!ifdef SHOW_Protostub1AtRuntimeB
			participant "SP1\nprotoStub" as Proto1@B
			!endif
		end box
	!endif

	!ifdef SHOW_SP2SandboxAtRuntimeB
		box "Service Provider 2 Sandbox at Bob Device"
			!ifdef SHOW_Protostub2AtRuntimeB
			participant "SP2\nprotoStub" as Proto2@B
			!endif

			!ifdef SHOW_ServiceProvider2HypertyAtRuntimeB
			participant "Service Provider2\nHyperty" as SP2H@B
			!endif

			!ifdef SHOW_ServiceProvider2RouterAtRuntimeB
			participant "Service Provider2\nRouter" as Router2@B
			!endif
		end box
	!endif
!endif


!ifdef SHOW_Bob
	actor "Bob" as Bob
!endif
