
@startuml "discover-hyperty.png"

autonumber

!define SHOW_RuntimeA

!define SHOW_CoreRuntimeA
!define SHOW_MsgBUSAtRuntimeA
!define SHOW_RegistryAtRuntimeA

!define SHOW_SP1SandboxAtRuntimeA
!define SHOW_Protostub1AtRuntimeA
!define SHOW_ServiceProvider1HypertyAtRuntimeA

!define SHOW_SP1

!include ../runtime_objects.plantuml

== query Runtime Registry about available Hyperties for a User ==

SP1H@A -> SP1H@A : discoverHypertyPerUser( UserURL )

SP1H@A -> BUS@A : postMessage(\n READ Message \nto discover Hyperties )

BUS@A -> RunReg@A : postMessage(\n READ Message \nto discover Hyperties)

RunReg@A -> RunReg@A : is HypertyURL stored locally?

BUS@A <- RunReg@A : postMessage(\n READ Message \nto discover Hyperties)

BUS@A -> Proto1@A : postMessage(\n READ Message \nto discover Hyperties)

Proto1@A -> SP1 : discover Hyperties with SP1 MSG Protocol

Proto1@A <- SP1 : discovered Hyperties with SP1 MSG Protocol

BUS@A <- Proto1@A : postMessage(\n RESPONSE Message \nwith discovered Hyperties)

RunReg@A <- BUS@A : postMessage(\n RESPONSE Message \nwith discovered Hyperties)

RunReg@A <- RunReg@A : save discovered Hyperties locally

RunReg@A -> BUS@A : postMessage(\n RESPONSE Message \nwith discovered Hyperties)

SP1H@A <- BUS@A : postMessage(\n RESPONSE Message \nwith discovered Hyperties)



@enduml
