@startuml

node auth [ 
Authentication Server 
====

====
<b>ephemeral key generator
]
node sip [
Sip Server 
====

====
<b>kamailio
]
node media [ 
Media Server 
====

====
<b>FreeSwitch
]

sip -- media

@enduml