@startuml "Core_Runtime.png"

node "Service Provider" as SP {
}

() "Service Provider\nCatalogue Interface" as CatI



node "Runtime Device" as rt {

node "Service Provider Sandbox" as SPSand {

}

node "Core Sandbox" as core {

node "" as core1 {
 node "*            Message      BUS                *" as Bus

 node "Sync\nManager" as Sync

 node "Runtime\nRegistry" as Reg

 node "Identity\nModule" as ID

 node "Policy Engine" as PDP

 node "QoS\nUser Agent" as QoS

 node "Graph\nConnector" as Graph
}


 node "Runtime\nUser Agent" as RunUA {
	node "Catalogue Runtime" as RepUA
 }




 RunUA -> Reg : Register Hyperties\nand protostubs
 }

 RunUA .> core1 : deploy&manage

 PDP <-left- Bus : authorise

 PDP -down-> QoS : set QoS

 PDP -down-> ID : generate or\n verify assertions

 PDP -down-> Graph : is Trustful?

 Reg <-up- Bus: resolve\nmessage

 Sync <-down- Bus: manage\nsync

 RunUA -> Bus : add listener

 RunUA .up-> SPSand : deploy&manage

 SPSand <-> Bus : post Message

 	}

RepUA -up-> CatI : query and\n download \nCatalogue\n Objects

rt -[hidden]up- SP

SPSand -[hidden]up- CatI

CatI -up- SP


@enduml
