

@startuml "data-object-resume.png"

autonumber

!define SHOW_SP2

!define SHOW_RuntimeA

!define SHOW_CoreRuntimeA
!define SHOW_SMAtRuntimeA
!define SHOW_SP1SandboxAtRuntimeA
!define SHOW_Syncher1AtRuntimeA

!define SHOW_Runtime1B

!define SHOW_CoreRuntime1B
!define SHOW_SMAtRuntime1B
!define SHOW_RegistryAtRuntime1B
!define SHOW_SP1SandboxAtRuntime1B
!define SHOW_Syncher1AtRuntime1B

!include ../runtime_objects.plantuml

== check if there are Observer objects to be resumed ==

Sync1@1B -> RunSM@1B : Subscribe Msg

RunSM@1B -> RunSM@1B : are there stored\n subscribed data objects


alt yes

	loop for each Observer object to be resumed
			RunSM@1B -> RunSM@1B : bus.addListener\n( DataObjURL/changes, observerLSandboxListener)
	end

	Sync1@1B <-- RunSM@1B : response with\n local stored\nObserver objects

	== listeners are added on Hyperty side ==

	loop for each observer object to be resumed
		create ObserverObject
		Sync1@1B -> ObserverObject : new()

		Sync1@1B -> Sync1@1B : Minibus.Addlisteners(\nDataObjURL\changes,\nSyncherListener)
	end

	Sync1@1B -> Sync1@1B : onObserversResume()

== lets get the most updated version ==

	loop for each resumed Observer Object

		ObserverObject -> Sync1@A : Read Msg
		ObserverObject <-- Sync1@A : Read Response Msg \nwith most updated Data Object

		ObserverObject -> ObserverObject : onChanges()
	end
else no, Obserevr data objects to be resumed
	Sync1@1B <-- RunSM@1B : not found response

end

== check if there are Reporter objects to be resumed ==

Sync1@1B -> RunSM@1B : Create Msg

RunSM@1B -> RunSM@1B : are there stored\n Reporter data objects


alt yes

	loop for each Reporter object to be resumed
			RunSM@1B -> RunSM@1B : bus.addListener\n( DataObjURL/subscription, listener)
	end

	Sync1@1B <-- RunSM@1B : response with\n local stored \nreporter objects

	== listeners are added on Hyperty side ==


	loop for each reporter object to be resumed
		create ReporterObject
		Sync1@1B -> ReporterObject : new()

		Sync1@1B -> Sync1@1B : Minibus.Addlisteners(\nDataObjURL,\nSyncherListener)

		Sync1@1B -> RunReg@1B : send Update Message to <objectUrl>\status

			RunReg@1B -> SP2 : registry: Update Data Object Registration\n at Domain Registry Message

			note right
				Data Object registration status is
				 updated in the Domain Registry to "live"
			end note

			RunReg@1B <-- SP2 : Update Registration Response Message
	end

	Sync1@1B -> Sync1@1B : onReportersResume()

else no Reporter data objects to be resumed
	Sync1@1B <-- RunSM@1B : not found response

end


@enduml
