

@startuml "msg-node-with-gw.png"


node "Support Services" as ss {

}

node "Hyperty Runtime" as runtime {
	node "Protostub" as stub
}

node "Message Node Core" as core {

}

node "Message Node GW" as gw {
}

stub <-up-> gw : deliver support services msg\n&hyperty msg

core <-down-> gw : msg core protocol

ss <-down-> gw : Support Services Protocols


@enduml
