

@startuml "msg-node-with-nodess.png"


node "Support Services" as ss {

}

node "Hyperty Runtime" as runtime {
	node "Protostub" as stub
}

node "Message Node Core" as core {

}

node "Message Node SS" as nodeSS {
}


stub <-up-> core : deliver hyperty msg

stub <-up-> nodeSS : deliver support services msg

ss <-down-> nodeSS : Support Services Protocols

core <-down-> nodeSS : msg core\nmanagement protocol

@enduml
