

@startuml "bus-msg-routing.png"

autonumber

!define SHOW_RuntimeA

!define SHOW_CoreRuntimeA
!define SHOW_MsgBUSAtRuntimeA
!define SHOW_RegistryAtRuntimeA
!define SHOW_IdentitiesAtRuntimeA
!define SHOW_AuthAtRuntimeA

!define SHOW_SP1SandboxAtRuntimeA
!define SHOW_Protostub1AtRuntimeA

!define SHOW_SP1

!include ../runtime_objects.plantuml

-> BUS@A : postMsg(message)

RunReg@A <- BUS@A : resolve(Message)

RunReg@A -> RunReg@A  : verify source(association Id Token)

RunReg@A -> RunReg@A  : resolve target address

group option :unregistered P2P Protocol Stub for external address

	group discover P2P Protocol Stub URL

		group P2P Protocol Stub URL not stored locally

			RunReg@A -> RunReg@A : is HypertyURL stored locally?

			BUS@A <- RunReg@A : postMessage(\n READ Message \nto discover Hyperties)

			BUS@A -> Proto1@A : postMessage(\n READ Message \nto discover Hyperties)

			Proto1@A -> SP1 : discover Hyperties\n with SP1 MSG Protocol

			Proto1@A <- SP1 : discovered Hyperties\n with SP1 MSG Protocol

			BUS@A <- Proto1@A : postMessage(\n RESPONSE Message \nwith discovered Hyperties)

			RunReg@A <- BUS@A : postMessage(\n RESPONSE Message \nwith discovered Hyperties)

			RunReg@A <-RunReg@A : extract P2P \nRequester Catalogue URL

		end
	end

	group deploy P2P Protocol Stub
	end

end

group option :P2P Stub failed, unregistered Protocol Stub for external address

	group discover MN Protocol Stub URL
	end

	group deploy MN Protocol Stub
	end

end

RunReg@A -> BUS@A : return(ResolvedMessage)

loop until authorised or final error
	RunAuth@A <- BUS@A : authorise(Message)

	RunAuth@A -> RunAuth@A : apply authz Policies

	alt Message Routing authorised
		RunAuth@A -> BUS@A : authorised
	else

		alt assertion required
			RunAuth@A -> RunID@A : generateAssertion( message / scope? )

			RunAuth@A <- RunID@A : return Assertion


		else verify assertion
			RunAuth@A -> RunID@A : validateAssertion( message )
			RunAuth@A <- RunID@A : return validation
		end
	else
		RunAuth@A -> BUS@A : final error

		alt Error : unknown source

		else Error : target not found

		else Error : not associated with Identity

		else Error : blocked by source policy

		else Error : blocked by target policy
		end
	end
end


BUS@A ->  : send msg


@enduml
