

@startuml "bus-msg-routing.png"

autonumber

!define SHOW_RuntimeA

!define SHOW_CoreRuntimeA
!define SHOW_MsgBUSAtRuntimeA
!define SHOW_RegistryAtRuntimeA
!define SHOW_IdentitiesAtRuntimeA
!define SHOW_AuthAtRuntimeA


!include ../runtime_objects.plantuml

 BUS@A <- : postMsg(message)

group resolve-routing-address

  RunReg@A <- BUS@A : resolve(Message)

	...

	RunReg@A --> BUS@A : return(ResolvedMessage)

end

	RunAuth@A <- BUS@A : authorise(Message)

  alt assertion required
    RunAuth@A -> RunID@A : getIdentityOfHyperty( message / scope? )
    RunID@A -> RunID@A : generateAssertion( )

    RunAuth@A <- RunID@A : return Assertion
  else verify assertion
    RunAuth@A -> RunID@A : decrypt ( message )
    RunID@A -> RunID@A : validateIdentity( )
    RunID@A -> RunID@A : validateData( )
    RunAuth@A <- RunID@A : return message\n(decrypted and validated)
  end

	RunAuth@A -> RunAuth@A : apply authz Policies

	alt Message Routing authorised
		RunAuth@A -> BUS@A : authorised
	else error

		RunAuth@A -> BUS@A : final error

		alt Error : unknown source

		else Error : target not found

		else Error : not associated with Identity

		else Error : blocked by source policy

		else Error : blocked by target policy
		end
	end


BUS@A ->  : send msg


@enduml
