@startuml "deploy-runtime.png"

autonumber

!define SHOW_RuntimeA

!define SHOW_AppAtRuntimeA

participant "Catalogue App" as RunCatApp

!define SHOW_CoreRuntimeA
!define SHOW_MsgBUSAtRuntimeA
!define SHOW_RegistryAtRuntimeA
!define SHOW_IdentitiesAtRuntimeA
!define SHOW_AuthAtRuntimeA
!define SHOW_CoreAgentAtRuntimeA
!define SHOW_CatalogueAtRuntimeA
!define SHOW_SMAtRuntimeA

!define SHOW_SP1SandboxAtRuntimeA
!define SHOW_Protostub1AtRuntimeA

!define SHOW_CoreRuntimeProvider

!include ../runtime_objects.plantuml

== Deploy Core Runtime ==

create RunCatApp
App@A -> RunCatApp : new

App@A -> RunCatApp : getRuntime(RuntimeCatalogueURL)

group option : if most updated version of Runtime source package is not stored locally

  RunCatApp -> CoreRunSP : get RuntimeCatalogueURL

  RunCatApp <-- CoreRunSP : return Runtime descriptor

end group

App@A <-- RunCatApp : return Runtime

create RunUA@A
App@A -> RunUA@A : new

App@A -> RunUA@A : init

RunUA@A -> RunUA@A : reuse cached\n RuntimeURL

create RunCat@A
App@A -> RunCat@A : new

create RunReg@A
RunUA@A -> RunReg@A : new

create RunID@A
RunUA@A -> RunID@A : new

create RunAuth@A
RunUA@A -> RunAuth@A : new

create RunSM@A
RunUA@A -> RunSM@A : new

create BUS@A
RunUA@A -> BUS@A : new

RunUA@A -> RunSM@A : init( )

loop  Phase 2 New!! for each stored reporter subscription

  RunSM@A -> BUS@A : addListener\n( DataObjURL\changes, listener)

end

loop Phase 2 New!! for each stored observer subscription

  RunSM@A -> RunSM@A : addListener\n( DataObjURL\changes, observerListener)

end

group option : Phase 2 New!! if runtime is P2P enabled

  group : P2P Handler Stub is loaded (see protostub-load.md)

    RunUA@A -> RunUA@A : p2pConfig.isHandlerStub = true

    RunUA@A -> RunUA@A : loadStub( domain , p2pConfig )

    ...

  end group

  RunUA@A -> BUS@A : postMsg( subscribe P2PHandlerStubURL request message)

  note right
    the message delivery path has to be set in the Message Node
  end note

  BUS@A -> Proto1@A : send subscribe \nP2PHandlerStubURL \nrequest message

  group : it performs the Service Provider 1 domain protostub load, see protostub-load.md)

    create Proto1@A
    RunUA@A -> Proto1@A : new
    ...

  end group

  CoreRunSP <- Proto1@A : send subscribe \nP2PHandlerStubURL \nrequest message

  CoreRunSP <-- Proto1@A : subscribe \nP2PHandlerStubURL\n response message

  BUS@A <-- Proto1@A : subscribe \nP2PHandlerStubURL\n response message

  RunUA@A <- BUS@A : ontMsg( subscribe \nP2PHandlerStubURL \nresponse message)

end group



@enduml
