
@startuml "domain-login-implicit.png"

autonumber

!define SHOW_RuntimeA

!define SHOW_CoreRuntimeA
!define SHOW_MsgBUSAtRuntimeA

!define SHOW_SP1SandboxAtRuntimeA
!define SHOW_Protostub1AtRuntimeA
!define SHOW_ServiceProvider1HypertyAtRuntimeA

!define SHOW_SP1

!include ../runtime_objects.plantuml


    group First Message sent to Protocol Stub

        Proto1@A <- BUS@A : postMessage\n(1st Message\n+Access Token)

    end

    Proto1@A -> Proto1@A : not connected yet

    Proto1@A -> SP1 : connect(Access Token)

    SP1 -> SP1 : validate ID Token

    Proto1@A <- SP1 : Success\nSession Token Granted

    note over Proto1@A
        session token is handled by the protoStub
        or by the Registry?
    end note

    Proto1@A -> SP1 : 1st message\n(Session Token)

Proto1@A -> BUS@A : postMessage\n(UPDATE message with ProtoStub.status = connected)


@enduml
