
@startuml "user-registration.png"

autonumber

!define SHOW_RuntimeA

!define SHOW_AppAtRuntimeA

!define SHOW_CoreRuntimeA
!define SHOW_MsgBUSAtRuntimeA
!define SHOW_IdentitiesAtRuntimeA
!define SHOW_CoreAgentAtRuntimeA

!define SHOW_SP1SandboxAtRuntimeA
!define SHOW_Protostub1AtRuntimeA

!define SHOW_SP1

!include ../runtime_objects.plantuml


== Identity Account creation ==


App@A -> RunUA@A : registerIdentity\n(IdP URL and ID token)

== Deploy Protocol Stub ==

group deploy IdP Proxy Protocol Stub

  RunUA@A -> RunUA@A : loadProtoStub(..)

    note right
        detailed in a separated diagram
    end note

    create Proto1@A
    RunUA@A -> Proto1@A : new
end

RunUA@A -> RunID@A : registerIdentity\n(IdP URL and ID token)

RunID@A -> BUS@A : postMessage\n( GET IDToken Message )

Proto1@A  <- BUS@A : postMessage\n( GET IDToken Message )

Proto1@A -> SP1 : send GET \nIDToken SP1 Msg

SP1 -> Alice : Authentication and Authorisation

SP1 <- Alice : Authenticate and Authorise

SP1 -> Proto1@A : return Tokens

Proto1@A -> BUS@A : postMessage\n( Response Message with Tokens )

RunID@A <- BUS@A : postMessage\n( Response Message with Tokens  )

RunID@A -> RunID@A : store tokens



@enduml
