@startuml "../datamodel/Rethink-Core.png"

package RethinkCore <<Rect>> {

	class RethinkObject {
	}

	package SyncDataObject {
	}

	package GraphConnector <<Rect>> {
	}

	package CatalogueDataObject <<Rect>> {
	}

	package RegistryDataObject <<Rect>> {
	}

	package UserHypertyAccount <<Rect>> {
	}

	package Identity <<Rect>> {
	}

	package RethinkType <<Rect>> {
	}

	package Domain <<Rect>> {
	}
}

package Message <<Rect>> {
}

package URL <<Rect>> {
}

package Connection <<Rect>> {
}

package Communication <<Rect>> {
}

package Context <<Rect>> {
}

RethinkObject <|-- Identity

RethinkObject <|-- GraphConnector

RethinkObject <|-- CatalogueDataObject

RethinkObject <|-- RegistryDataObject

RethinkObject <|-- URL

RethinkObject <|-- Message

RethinkObject <|-- SyncDataObject

SyncDataObject <|-- Connection

SyncDataObject <|-- Communication

SyncDataObject <|-- Context

GraphConnector .down.> URL

CatalogueDataObject .down.> URL

RegistryDataObject .down.> URL

Identity .down.> URL

URL <.down. Message

@enduml
