@startuml


HypertyGovernance --> GovernancePolicies : expressed by
HypertyGovernance :
HypertyGovernance --> Management_AAA_QoS_Requirements : refined by
GovernancePolicies --> ManagementPolicies_AAAPolicies_QoSPolicies : refined by
Management_AAA_QoS_Requirements <--> ManagementPolicies_AAAPolicies_QoSPolicies : expressed by
ManagementPolicies_AAAPolicies_QoSPolicies --> Management_Services : control
ManagementPolicies_AAAPolicies_QoSPolicies --> Management_AAA_QoS_Services : control
Management_Services : publish / update / remove / register / unregister 
Management_AAA_QoS_Services : deploy / monitor / charge

@enduml
